<style>


    .nav {
        border-width: 1px 0;
        list-style: none;
        margin: 0;
        padding: 0;
        text-align: center;
        background-color: #333;
    }

    .nav li {
        display: inline;
    }

    .nav a {
        display: inline-block;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
        color: #f2f2f2;
    }
    .nav a:hover {
        background-color: #ddd;
        color: black;
    }

    .nav a.active {
        background-color: #04AA6D;
        color: white;
    }
</style>


<ul class="nav">
    <li><a href="index.php">Home</a></li>
    <li><a href="task1.php">Task 1</a></li>
    <li><a href="task2.php">Task 2</a></li>
    <li><a href="task3.php">Task 3</a></li>
    <li><a href="task4.php">Task 4</a></li>
    <li><a href="task5.php">Task 5</a></li>
    <li><a href="task6.php">Task 6</a></li>
    <li><a href="task7.php">Task 7</a></li>
    <li><a href="task8.php">Task 8</a></li>
    <li><a href="task9.php">Task 9</a></li>
    <li><a href="task10.php">Task 10</a></li>
</ul>