<style>


    .nav {
        border-width: 1px 0;
        list-style: none;
        margin: 0;
        padding: 0;
        text-align: center;
        background-color: #333;
    }

    .nav li {
        display: inline;
    }

    .nav a {
        display: inline-block;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
        color: #f2f2f2;
    }

    .nav a:hover {
        background-color: #ddd;
        color: black;
    }

    .nav a.active {
        background-color: #04AA6D;
        color: white;
    }
</style>


<ul class="nav">
    <li><a href="../task9.php">About</a></li>
    <li><a href="company.php">Companies</a></li>
    <li><a href="trucks.php">Trucks</a></li>
    <li><a href="levy.php">Levies</a></li>

</ul>